language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
script: nosetests
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
