language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - "pip install numpy"
  - "pip install scipy"
  - "pip install matplotlib"
script: 
  - "python dcf.py example/ts1.csv example/ts2.csv -200 200 0.8 -np"
